### ISSUE TITLE
What's the correct path of assets?

### ISSUE THREAD

**Issue by kanlidy** [KleoPetroff/react-webpack-boilerplate#191] opened 2017-09-01 07:59 UTC
## The problem

What's the correct path of assets? When I want to add some images to `assets` folder, like `asessts/img`, and use on my websites, I failed.

## Details

1. Do run dev mode:
```
npm run start
```

2. Add many images to `/assets/img/bg.jpg`

3. Add path to sass files.

```
.bg{
  background:url("./img/bg.jpg") no-repeat top center;
  height: 720px;
}
```

OR

```
.bg{
  background:url("./assets/img/bg.jpg") no-repeat top center;
  height: 720px;
}
```

I got 404 error of my images.

**Comment by khusainovk** [comment] 2017-09-06 10:10
Hey!
Try to do like [this](https://github.com/KleoPetroff/react-webpack-boilerplate/issues/193)

**Comment by KleoPetroff** [comment] 2017-09-06 13:56
Hi @kanlidy,

The problem was caused by `file-loader`. Reverting to 0.11.2, as @khusainovk stated, should fix the problem. I've already committed the changes with some other small structural changes and will create a new release by the end of the day.

**Closed** 2017-09-06 14:01 UTC
Labels: bug

**Comment by kanlidy** [comment] 2017-09-19 09:11
Thanks guys.

You solved my problem.

And those images in React JSX could use following way:

Import first:

`import imgObj from '../assets/images/logo.png';`

In your JSX:

`<img src={imgObj} width="36" height="44" alt="" />`
